apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docker-registry-pvc
  namespace: docker-registry
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: longhorn-custom
  resources:
    requests:
      storage: 2Gi
